/* eslint-disable no-undef, no-console */
import { build } from 'vite';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, '..');
const entry = resolve(
  appRoot,
  'src/pages/ui-generator-builder/editor/cm-editor-entry.ts'
);
const outFile = resolve(
  appRoot,
  'src/pages/ui-generator-builder/editor/editor-bundle.generated.js'
);

const result = await build({
  configFile: false,
  logLevel: 'warn',
  build: {
    write: false,
    target: 'es2020',
    minify: 'esbuild',
    lib: {
      entry,
      formats: ['iife'],
      name: 'EverestYamlEditor',
      fileName: () => 'editor-bundle.js',
    },
  },
});

const outputs = Array.isArray(result) ? result[0].output : result.output;
const chunk = outputs.find((o) => o.type === 'chunk');
if (!chunk) throw new Error('build-editor: no JS chunk produced');
const rawSource = chunk.code;

// Escape any literal "</script>" in the bundle (a minified bundle can contain it
// in a string/regex) so it's safe to inline verbatim in the iframe's <script>
// tag. "<\/script>" is a no-op for the JS parser; srcdoc.ts inlines this as-is.
const source = rawSource.replace(/<\/script/gi, '<\\/script');

const generated =
  `// AUTO-GENERATED by scripts/build-editor.mjs. Do not edit. Do not commit.\n` +
  `export const EDITOR_BUNDLE_SOURCE = ${JSON.stringify(source)};\n`;

writeFileSync(outFile, generated);
console.log(`build-editor: wrote ${outFile} (${source.length} bytes)`);
